import { PRODUCT_PRICES } from './pricing'

export type Product = {
  id: number
  slug: string
  name: string
  pricingKey: string
  icon: string
  category: string
  description: string
  gsm: number
  fits?: string[]
  details: string[]
  careInstructions: string[]
  sizes: string[]
  price: number
  image: string | null
}

export const products: Product[] = [
  {
    id: 1,
    slug: 'regular-fit-tee-200gsm',
    name: 'Regular Fit T-Shirt',
    pricingKey: 'Regular Fit Tee (200 GSM)',
    icon: '/icons/tee.png',
    category: 'T-Shirts',
    description: '200 GSM classic regular fit tee. Clean silhouette, ideal for everyday branding and bulk orders.',
    gsm: 200,
    fits: ['Regular'],
    details: ['200 GSM 100% combed cotton', 'Regular fit', 'Crew neck', 'Preshrunk fabric', 'Twin needle hem'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    price: PRODUCT_PRICES['Regular Fit Tee (200 GSM)'],
    image: '/products/regular-fit-tee-200gsm.jpg',
  },
  {
    id: 2,
    slug: 'boxy-fit-tee-200gsm',
    name: 'Boxy Fit T-Shirt',
    pricingKey: 'Boxy Fit Tee (200 GSM)',
    icon: '/icons/tee.png',
    category: 'T-Shirts',
    description: '200 GSM boxy fit tee. Dropped shoulders, relaxed body. Ideal for lifestyle and streetwear branding.',
    gsm: 200,
    fits: ['Boxy'],
    details: ['200 GSM 100% combed cotton', 'Boxy oversized fit', 'Drop shoulder', 'Crew neck', 'Preshrunk fabric'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    price: PRODUCT_PRICES['Boxy Fit Tee (200 GSM)'],
    image: '/products/boxy-fit-tee-200gsm.jpg',
  },
  {
    id: 3,
    slug: 'regular-fit-tee-260gsm',
    name: 'Regular Fit Heavyweight T-Shirt',
    pricingKey: 'Regular Fit Tee (260 GSM)',
    icon: '/icons/tee.png',
    category: 'T-Shirts',
    description: '260 GSM heavyweight regular fit tee. Structured feel, premium drape.',
    gsm: 260,
    fits: ['Regular'],
    details: ['260 GSM 100% combed cotton', 'Regular fit', 'Crew neck', 'Preshrunk fabric', 'Reinforced seams'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    price: PRODUCT_PRICES['Regular Fit Tee (260 GSM)'],
    image: '/products/regular-fit-tee-260gsm.jpg',
  },
  {
    id: 4,
    slug: 'boxy-fit-tee-260gsm',
    name: 'Boxy Fit Heavyweight T-Shirt',
    pricingKey: 'Boxy Fit Tee (260 GSM)',
    icon: '/icons/tee.png',
    category: 'T-Shirts',
    description: '260 GSM heavyweight boxy fit tee. Maximum structure, premium weight.',
    gsm: 260,
    fits: ['Boxy'],
    details: ['260 GSM 100% combed cotton', 'Boxy oversized fit', 'Drop shoulder', 'Crew neck', 'Reinforced seams'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    price: PRODUCT_PRICES['Boxy Fit Tee (260 GSM)'],
    image: '/products/boxy-fit-tee-260gsm.jpg',
  },
  {
    id: 5,
    slug: 'longsleeve-tee-260gsm',
    name: 'Longsleeve Tee',
    pricingKey: 'Longsleeve Tee (260 GSM)',
    icon: '/icons/longsleeve.png',
    category: 'Longsleeve',
    description: '260 GSM long sleeve tee. Regular fit, clean finish.',
    gsm: 260,
    details: ['260 GSM 100% combed cotton', 'Regular fit', 'Long sleeves', 'Crew neck', 'Ribbed cuffs'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    price: PRODUCT_PRICES['Longsleeve Tee (260 GSM)'],
    image: '/products/longsleeve-tee-260gsm.jpg',
  },
  {
    id: 6,
    slug: 'canvas-tote-bag',
    name: 'Canvas Tote Bag',
    pricingKey: 'Canvas Tote Bag',
    icon: '/icons/totebag.png',
    category: 'Accessories',
    description: '12oz natural canvas tote. Reinforced handles, gusset base.',
    gsm: 340,
    details: ['12oz (340 GSM) natural canvas', 'Reinforced 24" handles', 'Gusset base', '38cm x 42cm body'],
    careInstructions: ['Hand wash cold', 'Air dry', 'Do not machine wash', 'Iron on low'],
    sizes: ['One Size'],
    price: PRODUCT_PRICES['Canvas Tote Bag'],
    image: '/products/canvas-tote-bag.jpg',
  },
  {
    id: 7,
    slug: 'regular-fit-sweatshirt-320gsm',
    name: 'Regular Fit Sweatshirt',
    pricingKey: 'Regular Fit Sweatshirt (320 GSM)',
    icon: '/icons/sweatshirt.png',
    category: 'Sweatshirts',
    description: '320 GSM crewneck sweatshirt in regular fit.',
    gsm: 320,
    fits: ['Regular'],
    details: ['320 GSM 80/20 cotton-poly fleece', 'Regular fit', 'Crewneck collar', 'Ribbed cuffs and hem', 'Brushed inner fleece'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    price: PRODUCT_PRICES['Regular Fit Sweatshirt (320 GSM)'],
    image: '/products/regular-fit-sweatshirt-320gsm.jpg',
  },
  {
    id: 9,
    slug: 'regular-fit-hoodie-320gsm',
    name: 'Regular Fit Hoodie',
    pricingKey: 'Regular Fit Hoodie (320 GSM)',
    icon: '/icons/hoodie.png',
    category: 'Hoodies',
    description: '320 GSM pullover hoodie in regular fit. Kangaroo pocket, structured hood.',
    gsm: 320,
    fits: ['Regular'],
    details: ['320 GSM 80/20 cotton-poly fleece', 'Regular fit', 'Kangaroo pocket', 'Structured hood with drawcord', 'Ribbed cuffs and hem'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    price: PRODUCT_PRICES['Regular Fit Hoodie (320 GSM)'],
    image: '/products/regular-fit-hoodie-320gsm.jpg',
  },
  {
    id: 10,
    slug: 'boxy-fit-hoodie-320gsm',
    name: 'Boxy Fit Hoodie',
    pricingKey: 'Boxy Fit Hoodie (320 GSM)',
    icon: '/icons/hoodie.png',
    category: 'Hoodies',
    description: '320 GSM pullover hoodie in boxy fit. Oversized hood, dropped shoulders.',
    gsm: 320,
    fits: ['Boxy'],
    details: ['320 GSM 80/20 cotton-poly fleece', 'Boxy oversized fit', 'Drop shoulder', 'Kangaroo pocket', 'Oversized hood with drawcord'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    price: PRODUCT_PRICES['Boxy Fit Hoodie (320 GSM)'],
    image: '/products/boxy-fit-hoodie-320gsm.jpg',
  },
]

export const categories = ['T-Shirts', 'Longsleeve', 'Sweatshirts', 'Hoodies', 'Accessories']
