export type Product = {
  id: number
  slug: string
  name: string
  category: string
  description: string
  gsm: number
  fits?: string[]
  details: string[]
  careInstructions: string[]
  sizes: string[]
  sizeChart?: { size: string; chest: string; length: string; shoulder?: string }[]
  price: number
  image: string | null
}

export const products: Product[] = [
  // T-SHIRTS
  {
    id: 1,
    slug: 'regular-fit-tee-200gsm',
    name: 'Regular Fit T-Shirt',
    category: 'T-Shirts',
    description: '200 GSM classic regular fit tee. Clean silhouette, ideal for everyday branding and bulk orders.',
    gsm: 200,
    fits: ['Regular'],
    details: ['200 GSM 100% combed cotton', 'Regular fit', 'Crew neck', 'Preshrunk fabric', 'Twin needle hem'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '34"', length: '26"', shoulder: '16"' },
      { size: 'S', chest: '36"', length: '27"', shoulder: '17"' },
      { size: 'M', chest: '38"', length: '28"', shoulder: '18"' },
      { size: 'L', chest: '40"', length: '29"', shoulder: '19"' },
      { size: 'XL', chest: '42"', length: '30"', shoulder: '20"' },
      { size: 'XXL', chest: '44"', length: '31"', shoulder: '21"' },
    ],
    price: 280,
    image: null,
  },
  {
    id: 2,
    slug: 'boxy-fit-tee-200gsm',
    name: 'Boxy Fit T-Shirt',
    category: 'T-Shirts',
    description: '200 GSM boxy fit tee. Dropped shoulders, relaxed body. Ideal for lifestyle and streetwear branding.',
    gsm: 200,
    fits: ['Boxy'],
    details: ['200 GSM 100% combed cotton', 'Boxy oversized fit', 'Drop shoulder', 'Crew neck', 'Preshrunk fabric'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '38"', length: '27"', shoulder: '19"' },
      { size: 'S', chest: '40"', length: '28"', shoulder: '20"' },
      { size: 'M', chest: '42"', length: '29"', shoulder: '21"' },
      { size: 'L', chest: '44"', length: '30"', shoulder: '22"' },
      { size: 'XL', chest: '46"', length: '31"', shoulder: '23"' },
      { size: 'XXL', chest: '48"', length: '32"', shoulder: '24"' },
    ],
    price: 280,
    image: null,
  },
  {
    id: 3,
    slug: 'regular-fit-tee-260gsm',
    name: 'Regular Fit Heavyweight T-Shirt',
    category: 'T-Shirts',
    description: '260 GSM heavyweight regular fit tee. Structured feel, premium drape. For brands that want to stand out.',
    gsm: 260,
    fits: ['Regular'],
    details: ['260 GSM 100% combed cotton', 'Regular fit', 'Crew neck', 'Preshrunk fabric', 'Reinforced seams'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '34"', length: '26"', shoulder: '16"' },
      { size: 'S', chest: '36"', length: '27"', shoulder: '17"' },
      { size: 'M', chest: '38"', length: '28"', shoulder: '18"' },
      { size: 'L', chest: '40"', length: '29"', shoulder: '19"' },
      { size: 'XL', chest: '42"', length: '30"', shoulder: '20"' },
      { size: 'XXL', chest: '44"', length: '31"', shoulder: '21"' },
    ],
    price: 340,
    image: null,
  },
  {
    id: 4,
    slug: 'boxy-fit-tee-260gsm',
    name: 'Boxy Fit Heavyweight T-Shirt',
    category: 'T-Shirts',
    description: '260 GSM heavyweight boxy fit tee. Maximum structure, premium weight. The go-to for serious merch.',
    gsm: 260,
    fits: ['Boxy'],
    details: ['260 GSM 100% combed cotton', 'Boxy oversized fit', 'Drop shoulder', 'Crew neck', 'Reinforced seams'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '38"', length: '27"', shoulder: '19"' },
      { size: 'S', chest: '40"', length: '28"', shoulder: '20"' },
      { size: 'M', chest: '42"', length: '29"', shoulder: '21"' },
      { size: 'L', chest: '44"', length: '30"', shoulder: '22"' },
      { size: 'XL', chest: '46"', length: '31"', shoulder: '23"' },
      { size: 'XXL', chest: '48"', length: '32"', shoulder: '24"' },
    ],
    price: 340,
    image: null,
  },
  // LONG SLEEVE
  {
    id: 5,
    slug: 'longsleeve-tee-260gsm',
    name: 'Long Sleeve T-Shirt',
    category: 'Long Sleeve',
    description: '260 GSM long sleeve tee. Regular fit, clean finish. Works year-round as a base layer or standalone piece.',
    gsm: 260,
    details: ['260 GSM 100% combed cotton', 'Regular fit', 'Long sleeves', 'Crew neck', 'Ribbed cuffs'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '34"', length: '27"', shoulder: '16"' },
      { size: 'S', chest: '36"', length: '28"', shoulder: '17"' },
      { size: 'M', chest: '38"', length: '29"', shoulder: '18"' },
      { size: 'L', chest: '40"', length: '30"', shoulder: '19"' },
      { size: 'XL', chest: '42"', length: '31"', shoulder: '20"' },
      { size: 'XXL', chest: '44"', length: '32"', shoulder: '21"' },
    ],
    price: 420,
    image: null,
  },
  // TOTE BAG
  {
    id: 6,
    slug: 'canvas-tote-bag',
    name: 'Canvas Tote Bag',
    category: 'Accessories',
    description: '12oz natural canvas tote. Reinforced handles, gusset base. The staple for cafes, events, and retail brands.',
    gsm: 340,
    details: ['12oz (340 GSM) natural canvas', 'Reinforced 24" handles', 'Gusset base for structure', '38cm x 42cm body', 'Natural undyed canvas'],
    careInstructions: ['Hand wash cold', 'Air dry', 'Do not machine wash', 'Iron on low'],
    sizes: ['One Size'],
    price: 180,
    image: null,
  },
  // SWEATSHIRT
  {
    id: 7,
    slug: 'regular-fit-sweatshirt-320gsm',
    name: 'Regular Fit Sweatshirt',
    category: 'Sweatshirts',
    description: '320 GSM crewneck sweatshirt in regular fit. Clean, structured silhouette. Ideal for corporate and hospitality branding.',
    gsm: 320,
    fits: ['Regular'],
    details: ['320 GSM 80/20 cotton-poly fleece', 'Regular fit', 'Crewneck collar', 'Ribbed cuffs and hem', 'Brushed inner fleece'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '36"', length: '25"', shoulder: '17"' },
      { size: 'S', chest: '38"', length: '26"', shoulder: '18"' },
      { size: 'M', chest: '40"', length: '27"', shoulder: '19"' },
      { size: 'L', chest: '42"', length: '28"', shoulder: '20"' },
      { size: 'XL', chest: '44"', length: '29"', shoulder: '21"' },
      { size: 'XXL', chest: '46"', length: '30"', shoulder: '22"' },
    ],
    price: 580,
    image: null,
  },
  {
    id: 8,
    slug: 'boxy-fit-sweatshirt-320gsm',
    name: 'Boxy Fit Sweatshirt',
    category: 'Sweatshirts',
    description: '320 GSM crewneck sweatshirt in boxy fit. Dropped shoulders, relaxed body. Made for lifestyle and creative brands.',
    gsm: 320,
    fits: ['Boxy'],
    details: ['320 GSM 80/20 cotton-poly fleece', 'Boxy oversized fit', 'Drop shoulder', 'Crewneck collar', 'Brushed inner fleece'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '40"', length: '26"', shoulder: '20"' },
      { size: 'S', chest: '42"', length: '27"', shoulder: '21"' },
      { size: 'M', chest: '44"', length: '28"', shoulder: '22"' },
      { size: 'L', chest: '46"', length: '29"', shoulder: '23"' },
      { size: 'XL', chest: '48"', length: '30"', shoulder: '24"' },
      { size: 'XXL', chest: '50"', length: '31"', shoulder: '25"' },
    ],
    price: 580,
    image: null,
  },
  // SWEATPANTS
  {
    id: 11,
    slug: 'regular-fit-sweatpants-320gsm',
    name: 'Regular Fit Sweatpants',
    category: 'Bottoms',
    description: '320 GSM fleece sweatpants in regular fit. Elastic waist with drawcord, side pockets, ribbed ankle cuffs.',
    gsm: 320,
    fits: ['Regular'],
    details: ['320 GSM 80/20 cotton-poly fleece', 'Regular fit', 'Elastic waist with drawcord', 'Two side pockets', 'Ribbed ankle cuffs', 'Brushed inner fleece'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '26"', length: '38"', shoulder: '10"' },
      { size: 'S', chest: '28"', length: '39"', shoulder: '10"' },
      { size: 'M', chest: '30"', length: '40"', shoulder: '11"' },
      { size: 'L', chest: '32"', length: '41"', shoulder: '11"' },
      { size: 'XL', chest: '34"', length: '42"', shoulder: '12"' },
      { size: 'XXL', chest: '36"', length: '43"', shoulder: '12"' },
    ],
    price: 580,
    image: null,
  },
  {
    id: 12,
    slug: 'boxy-fit-sweatpants-320gsm',
    name: 'Boxy Fit Sweatpants',
    category: 'Bottoms',
    description: '320 GSM fleece sweatpants in boxy relaxed fit. Wide leg, elastic waist with drawcord. Pairs with the boxy tee and hoodie.',
    gsm: 320,
    fits: ['Boxy'],
    details: ['320 GSM 80/20 cotton-poly fleece', 'Boxy wide leg fit', 'Elastic waist with drawcord', 'Two side pockets', 'Open hem', 'Brushed inner fleece'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '30"', length: '38"', shoulder: '11"' },
      { size: 'S', chest: '32"', length: '39"', shoulder: '11"' },
      { size: 'M', chest: '34"', length: '40"', shoulder: '12"' },
      { size: 'L', chest: '36"', length: '41"', shoulder: '12"' },
      { size: 'XL', chest: '38"', length: '42"', shoulder: '13"' },
      { size: 'XXL', chest: '40"', length: '43"', shoulder: '13"' },
    ],
    price: 580,
    image: null,
  },
  // SHORTS
  {
    id: 13,
    slug: 'regular-fit-shorts',
    name: 'Regular Fit Shorts',
    category: 'Bottoms',
    description: '220 GSM cotton shorts in regular fit. Elastic waist with drawcord, side pockets. Ideal for gyms, sports teams, and hospitality.',
    gsm: 220,
    fits: ['Regular'],
    details: ['220 GSM 100% combed cotton', 'Regular fit', '7" inseam', 'Elastic waist with drawcord', 'Two side pockets', 'Clean hemline'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '26"', length: '17"', shoulder: '7"' },
      { size: 'S', chest: '28"', length: '17.5"', shoulder: '7"' },
      { size: 'M', chest: '30"', length: '18"', shoulder: '7"' },
      { size: 'L', chest: '32"', length: '18.5"', shoulder: '7"' },
      { size: 'XL', chest: '34"', length: '19"', shoulder: '7"' },
      { size: 'XXL', chest: '36"', length: '19.5"', shoulder: '7"' },
    ],
    price: 320,
    image: null,
  },
  // DOCTOR TEE
  {
    id: 14,
    slug: 'doctor-tee-260gsm',
    name: 'Doctor Tee',
    category: 'T-Shirts',
    description: '260 GSM elongated doctor tee. Extended length, curved hem, slightly boxy fit. Clean minimal silhouette for lifestyle and streetwear brands.',
    gsm: 260,
    fits: ['Boxy'],
    details: ['260 GSM 100% combed cotton', 'Elongated boxy fit', 'Curved dropped hem', 'Extended length (+4" vs regular)', 'Drop shoulder', 'Crew neck'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '40"', length: '32"', shoulder: '20"' },
      { size: 'S', chest: '42"', length: '33"', shoulder: '21"' },
      { size: 'M', chest: '44"', length: '34"', shoulder: '22"' },
      { size: 'L', chest: '46"', length: '35"', shoulder: '23"' },
      { size: 'XL', chest: '48"', length: '36"', shoulder: '24"' },
      { size: 'XXL', chest: '50"', length: '37"', shoulder: '25"' },
    ],
    price: 360,
    image: null,
  },
  // HOODIE
  {
    id: 9,
    slug: 'regular-fit-hoodie-320gsm',
    name: 'Regular Fit Hoodie',
    category: 'Hoodies',
    description: '320 GSM pullover hoodie in regular fit. Kangaroo pocket, structured hood. The most versatile piece in the catalogue.',
    gsm: 320,
    fits: ['Regular'],
    details: ['320 GSM 80/20 cotton-poly fleece', 'Regular fit', 'Kangaroo pocket', 'Structured hood with drawcord', 'Ribbed cuffs and hem'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '36"', length: '26"', shoulder: '17"' },
      { size: 'S', chest: '38"', length: '27"', shoulder: '18"' },
      { size: 'M', chest: '40"', length: '28"', shoulder: '19"' },
      { size: 'L', chest: '42"', length: '29"', shoulder: '20"' },
      { size: 'XL', chest: '44"', length: '30"', shoulder: '21"' },
      { size: 'XXL', chest: '46"', length: '31"', shoulder: '22"' },
    ],
    price: 650,
    image: null,
  },
  {
    id: 10,
    slug: 'boxy-fit-hoodie-320gsm',
    name: 'Boxy Fit Hoodie',
    category: 'Hoodies',
    description: '320 GSM pullover hoodie in boxy fit. Oversized hood, dropped shoulders. Built for brands that lean streetwear.',
    gsm: 320,
    fits: ['Boxy'],
    details: ['320 GSM 80/20 cotton-poly fleece', 'Boxy oversized fit', 'Drop shoulder', 'Kangaroo pocket', 'Oversized hood with drawcord'],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'XS', chest: '42"', length: '27"', shoulder: '21"' },
      { size: 'S', chest: '44"', length: '28"', shoulder: '22"' },
      { size: 'M', chest: '46"', length: '29"', shoulder: '23"' },
      { size: 'L', chest: '48"', length: '30"', shoulder: '24"' },
      { size: 'XL', chest: '50"', length: '31"', shoulder: '25"' },
      { size: 'XXL', chest: '52"', length: '32"', shoulder: '26"' },
    ],
    price: 650,
    image: null,
  },
]

export const categories = ['T-Shirts', 'Long Sleeve', 'Sweatshirts', 'Hoodies', 'Accessories']